# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Snowbeat
email: chris@snowbeat.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The folio and blog of Christopher Bews, a front-end developer in London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://snowbeat.co.uk" # the base hostname & protocol for your site
twitter_username: koshiro
github_username:  ChrisBews
permalink: /:categories/:year/:title/
# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
exclude: [node_modules, gulpfile.js]